version: "3"

services:

    nginx:
        image: nginx
        environment:
              TZ: Europe/Moscow
        volumes:
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - front
            - backend
        ports:
            - "80:80"

    apache:
        build: ./docker/apache
        environment:
              TZ: Europe/Moscow
        volumes:
            - ./:/var/www/
            - ./docker/apache/php.ini:/usr/local/etc/php/php.ini
        networks:
            - backend

    db:
        image: mysql:5.7
        volumes:
            - ./docker/db:/var/lib/mysql
            - ./docker/db/logs:/var/log/mysql"
        restart: unless-stopped
        environment:
              TZ: Europe/Moscow
              MYSQL_ROOT_PASSWORD: root
              MYSQL_DATABASE: local
              MYSQL_USER: local
              MYSQL_PASSWORD: local
        networks:
              backend:
                   ipv4_address: 172.20.0.4
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        environment:
            - PMA_HOST=db
            - PMA_USER=root
            - PMA_PASSWORD=root
        volumes:
            - /sessions
        networks:
            - backend

networks:
    front:
        external:
            name: front
    backend:
        ipam:
           driver: default
           config:
            - subnet: 172.20.0.0/16